In [1]:
import torch
print(torch.__version__)
import numpy as np

2.3.1


In [2]:
scalar = torch.tensor(3)
scalar.ndim

0

In [3]:
scalar.item()

3

In [4]:
vector = torch.tensor([1, 7])
vector.ndim

1

In [5]:
vector.shape

torch.Size([2])

In [6]:
matrix = torch.tensor([[4, 6], [7, 9]])
matrix.ndim

2

In [7]:
matrix.shape

torch.Size([2, 2])

In [8]:
matrix

tensor([[4, 6],
        [7, 9]])

In [9]:
tensor1 = torch.tensor([[[1, 2, 3], [3, 4, 5], [5, 6, 7]]])
tensor1

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [10]:
#losowe wartości
tensor2 = torch.rand(4, 5)
tensor2

tensor([[0.7531, 0.1040, 0.6844, 0.0813, 0.4563],
        [0.7269, 0.2042, 0.9869, 0.7403, 0.9982],
        [0.7125, 0.1548, 0.8062, 0.6509, 0.8182],
        [0.0588, 0.6646, 0.2342, 0.9072, 0.5795]])

In [11]:
tensor2.ndim

2

In [12]:
#tensor z samymi zerami
tensor3 = torch.zeros(size=(3, 2))
tensor3

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
#tensor z samymi jedynkami
tensor4 = torch.ones(size=(5, 7))
tensor4

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [14]:
print(f'Typ wartości w tensorze utworzonym: {tensor1.dtype}')
print(f'Typ wartości w tensorze losowym: {tensor2.dtype}')
print(f'Typ wartości w tensorze z zerami: {tensor3.dtype}')
print(f'Typ wartości w tensorze z jedynkami: {tensor4.dtype}')

Typ wartości w tensorze utworzonym: torch.int64
Typ wartości w tensorze losowym: torch.float32
Typ wartości w tensorze z zerami: torch.float32
Typ wartości w tensorze z jedynkami: torch.float32


In [15]:
tensor5 = torch.arange(0, 15)
print(f'Typ wartości w tensorze z wykorzystaniem arange(): {tensor5.dtype}')

Typ wartości w tensorze z wykorzystaniem arange(): torch.int64


In [16]:
tensor6 = torch.arange(start=0, end=100, step=17)
tensor6

tensor([ 0, 17, 34, 51, 68, 85])

In [17]:
tensor7 = torch.tensor([4.0, 6.0, 9.0],
                      dtype=None)
print(f'Typ wartości w utworzonym tensorze: {tensor7.dtype}')

Typ wartości w utworzonym tensorze: torch.float32


In [18]:
tensor8 = torch.tensor([4.0, 6.0, 9.0],
                      dtype=torch.float16,
                      device=None,
                      requires_grad=False)
print(f'Typ wartości w utworzonym tensorze: {tensor8.dtype}')

Typ wartości w utworzonym tensorze: torch.float16


In [19]:
#convert float32 to float16
tensor9 = torch.tensor([7.4, 6.9, 9.2])
print(f'Typ wartości w utworzonym tensorze: {tensor9.dtype}')
tensor10 = tensor9.type(torch.float16)
print(f'Typ wartości w utworzonym tensorze: {tensor10.dtype}')

Typ wartości w utworzonym tensorze: torch.float32
Typ wartości w utworzonym tensorze: torch.float16


In [20]:
%%time
value = 0
for x in range(len(tensor9)):
    value += tensor9[x] * tensor9[x]

CPU times: total: 31.2 ms
Wall time: 13 ms


In [21]:
%%time
value2 = torch.matmul(tensor9, tensor9)

CPU times: total: 0 ns
Wall time: 19.9 ms


In [22]:
tensor_A = torch.tensor([[4, 6],
                        [8, 3],
                        [1, 2]])
tensor_B = torch.tensor([[0, 4],
                        [5, 7],
                        [7, 3]])
torch.matmul(tensor_A, tensor_B.T), torch.mm(tensor_A, tensor_B.T)

(tensor([[24, 62, 46],
         [12, 61, 65],
         [ 8, 19, 13]]),
 tensor([[24, 62, 46],
         [12, 61, 65],
         [ 8, 19, 13]]))

In [23]:
torch.mm(tensor_A.T, tensor_B)

tensor([[47, 75],
        [29, 51]])

In [24]:
tensor_A, tensor_A.T

(tensor([[4, 6],
         [8, 3],
         [1, 2]]),
 tensor([[4, 8, 1],
         [6, 3, 2]]))

In [25]:
tensor_B, tensor_B.T

(tensor([[0, 4],
         [5, 7],
         [7, 3]]),
 tensor([[0, 5, 7],
         [4, 7, 3]]))

In [26]:
tensor11 = torch.tensor([4.9, 7, 1.0, 8.4, 1.43, .04, 84.3, 205.4, 205.41, -22.1, -14, -22.1005])
tensor11, tensor11.dtype

(tensor([ 4.9000e+00,  7.0000e+00,  1.0000e+00,  8.4000e+00,  1.4300e+00,
          4.0000e-02,  8.4300e+01,  2.0540e+02,  2.0541e+02, -2.2100e+01,
         -1.4000e+01, -2.2101e+01]),
 torch.float32)

In [27]:
torch.min(tensor11), tensor11.min()

(tensor(-22.1005), tensor(-22.1005))

In [28]:
torch.max(tensor11), tensor11.max()

(tensor(205.4100), tensor(205.4100))

In [29]:
#Muszą w funkcji mean() byc wartości float inaczej nie będzie działać
torch.mean(tensor11.type(torch.float32)), tensor11.type(torch.float32).mean()

(tensor(38.3066), tensor(38.3066))

In [30]:
torch.sum(tensor11), tensor11.sum()

(tensor(459.6795), tensor(459.6795))

In [31]:
tensor11.argmax(), tensor11.argmin()

(tensor(8), tensor(11))

In [32]:
#Dostosowywanie rozmiaru
tensor11.reshape(1, 12)

tensor([[ 4.9000e+00,  7.0000e+00,  1.0000e+00,  8.4000e+00,  1.4300e+00,
          4.0000e-02,  8.4300e+01,  2.0540e+02,  2.0541e+02, -2.2100e+01,
         -1.4000e+01, -2.2101e+01]])

In [33]:
tensor11.reshape(12, 1)

tensor([[ 4.9000e+00],
        [ 7.0000e+00],
        [ 1.0000e+00],
        [ 8.4000e+00],
        [ 1.4300e+00],
        [ 4.0000e-02],
        [ 8.4300e+01],
        [ 2.0540e+02],
        [ 2.0541e+02],
        [-2.2100e+01],
        [-1.4000e+01],
        [-2.2101e+01]])

In [34]:
tensor11.reshape(4, 3)

tensor([[ 4.9000e+00,  7.0000e+00,  1.0000e+00],
        [ 8.4000e+00,  1.4300e+00,  4.0000e-02],
        [ 8.4300e+01,  2.0540e+02,  2.0541e+02],
        [-2.2100e+01, -1.4000e+01, -2.2101e+01]])

In [35]:
tensor11.reshape(3, 4)

tensor([[ 4.9000e+00,  7.0000e+00,  1.0000e+00,  8.4000e+00],
        [ 1.4300e+00,  4.0000e-02,  8.4300e+01,  2.0540e+02],
        [ 2.0541e+02, -2.2100e+01, -1.4000e+01, -2.2101e+01]])

In [36]:
tensor12 = torch.arange(1, 13, dtype=torch.float32)
tensor12

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [37]:
tensor12_view = tensor12.view(1, 12)
tensor12_view, tensor12_view.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [38]:
#Zmienianie widoku tensora powoduje zmiane jego samego, ponieważ dzielą ten sam adres
tensor12_view[:, 0] = 7
tensor12, tensor12_view

(tensor([ 7.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([[ 7.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]))

In [39]:
tensor13 = torch.stack([tensor12, tensor12, tensor12], dim=0)
tensor13

tensor([[ 7.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 7.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 7.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [40]:
tensor14 = torch.stack([tensor12, tensor12, tensor12], dim=1)
tensor14

tensor([[ 7.,  7.,  7.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.],
        [11., 11., 11.],
        [12., 12., 12.]])

In [41]:
#Usuwanie pojedynczych wymiarów z tensora za pomocą funkcji squeeze()
tensor15 = torch.arange(0, 12).reshape(1, 12)
print(f'Tensor przed zmianą:', tensor15)
print(f'Wymiary tensora przed zmianą: {tensor15.shape}')
tensor15 = tensor15.squeeze()
print(f'\nTensor po zmianie:', tensor15)
print(f'Wymiary tensora po zmianie: {tensor15.shape}')

Tensor przed zmianą: tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])
Wymiary tensora przed zmianą: torch.Size([1, 12])

Tensor po zmianie: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Wymiary tensora po zmianie: torch.Size([12])


In [42]:
#Dodanie dodatkowego wymiaru za pomocą funkcji unsqueeze()
print(f'Tensor przed zmianą:', tensor15)
print(f'Wymiary tensora przed zmianą: {tensor15.shape}')
tensor15 = tensor15.unsqueeze(dim=0)
print(f'\nTensor po zmianie:', tensor15)
print(f'Wymiary tensora po zmianie: {tensor15.shape}')

Tensor przed zmianą: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Wymiary tensora przed zmianą: torch.Size([12])

Tensor po zmianie: tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])
Wymiary tensora po zmianie: torch.Size([1, 12])


In [43]:
#Zamiana kolejności w wymiarach za pomocą funkcji permute()
tensor16 = torch.rand(size=(224, 224, 3))
print(f'Rozmiar tensora przed zmianą: {tensor16.shape}')
tensor16 = tensor16.permute(2, 0, 1)
print(f'Rozmiar tensora po zmianie: {tensor16.shape}')

Rozmiar tensora przed zmianą: torch.Size([224, 224, 3])
Rozmiar tensora po zmianie: torch.Size([3, 224, 224])


In [44]:
#Inny przykład ze zmianą kolejności z wymiarami
tensor17 = torch.arange(1, 25).reshape(2, 3, 4)
print(f'Rozmiar tensora przed zmianą: {tensor17.shape}')
print(f'Tensor przed zmianą:\n', tensor17)
print(f'Przykładowa wartość przed zmianą: {tensor17[0, 1, 2]}')
tensor17 = tensor17.permute(2, 0, 1)
print(f'Rozmiar tensora po zmianie: {tensor17.shape}')
print(f'Tensor po zmianie:\n', tensor17)
print(f'Przykładowa wartość po zmianie: {tensor17[0, 1, 2]}')

Rozmiar tensora przed zmianą: torch.Size([2, 3, 4])
Tensor przed zmianą:
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
Przykładowa wartość przed zmianą: 7
Rozmiar tensora po zmianie: torch.Size([4, 2, 3])
Tensor po zmianie:
 tensor([[[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]],

        [[ 4,  8, 12],
         [16, 20, 24]]])
Przykładowa wartość po zmianie: 21


In [45]:
#Testowanie posługiwanie sie indeksami tensora
tensor17 = torch.arange(1, 13).reshape(1, 3, 4)
tensor17, tensor17.shape

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]]]),
 torch.Size([1, 3, 4]))

In [46]:
tensor17[0, :, 1]

tensor([ 2,  6, 10])

In [47]:
tensor17[0, 1, 1], tensor17[0][1][1]

(tensor(6), tensor(6))

In [48]:
tensor17[:, :, 3]

tensor([[ 4,  8, 12]])

In [49]:
tensor17[0, 0, 0], tensor17[0, 1, 0], tensor17[0, -1, 0], tensor17[0, 0, 1], tensor17[0, 0, -1]

(tensor(1), tensor(5), tensor(9), tensor(2), tensor(4))

In [50]:
tensor17[:, 0, 0], tensor17[0, :, 0], tensor17[0, 0, :]

(tensor([1]), tensor([1, 5, 9]), tensor([1, 2, 3, 4]))

In [51]:
#Konwertowanie tablicy z biblioteki numpy do pytorch i na odwrót
array1 = np.arange(1.0, 10.0)
tensor18 = torch.from_numpy(array1)
array1, array1.dtype, tensor18, tensor18.dtype

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64),
 torch.float64)

In [52]:
#Pytorch podczas zmiany z numpy na pytorch nadaje tablicy typ float64, zaś przy normalnym tworzeniu jest to typ float32
torch.arange(1.0, 1.5).dtype

torch.float32

In [53]:
#Typ zmiany można ustalić
torch19 = torch.from_numpy(array1).type(torch.float32)
torch19.dtype

torch.float32

In [54]:
tensor20 = torch.ones(9)
array2 = tensor20.numpy()
tensor20.dtype, array2.dtype

(torch.float32, dtype('float32'))

In [55]:
tensor_C = torch.rand(3, 4)
tensor_D = torch.rand(3, 4)

print(tensor_C)
print(tensor_D)
print(tensor_C == tensor_D)

tensor([[0.1197, 0.1538, 0.5022, 0.9742],
        [0.2978, 0.3381, 0.5967, 0.5457],
        [0.7069, 0.9622, 0.5988, 0.8722]])
tensor([[0.6205, 0.0017, 0.0064, 0.2902],
        [0.9858, 0.2342, 0.6687, 0.3058],
        [0.7590, 0.0355, 0.5388, 0.2021]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [56]:
#Manipulowanie wartościami losowymi za pomocą manual_seed()
random_seed = 19

torch.manual_seed(random_seed)
tensor_E = torch.rand(3, 4)

torch.manual_seed(random_seed)
tensor_F = torch.rand(3, 4)

print(tensor_E)
print(tensor_F)
print(tensor_E == tensor_F)

tensor([[0.9686, 0.1999, 0.8799, 0.6622],
        [0.2161, 0.1192, 0.3617, 0.0167],
        [0.8503, 0.9620, 0.2479, 0.2946]])
tensor([[0.9686, 0.1999, 0.8799, 0.6622],
        [0.2161, 0.1192, 0.3617, 0.0167],
        [0.8503, 0.9620, 0.2479, 0.2946]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [57]:
torch.cuda.is_available(), torch.cpu.is_available()

(False, True)