In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
torch.manual_seed(42)

# Dane wejściowe i wyjściowe
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]], requires_grad=True)
y = torch.tensor([[2.0], [3.0], [4.0], [5.0]])

# Definicja modelu liniowego
model = nn.Linear(1, 1)

# Ustawienie innych wartości wagi i przesunięcia
model.weight.data.fill_(1.0)
model.bias.data.fill_(0.5)

# Funkcja strat
criterion = nn.MSELoss()

# Optymalizator
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Liczba epok
epochs = 3

for epoch in range(epochs):
    print(f'Initial weights: {model.weight}')
    print(f'Initial bias: {model.bias}\n')
    
    # Przewidywanie
    y_pred = model(X)
    
    # Obliczanie straty
    loss = criterion(y_pred, y)
    
    # Zerowanie gradientów
    optimizer.zero_grad()
    
    # Obliczanie gradientów
    loss.backward()
    
    # Aktualizacja wag
    optimizer.step()
    
    # Wyświetlanie straty
    print(f'Outputs: {y_pred}\n')
    print(f'Epoch {epoch+1}, Loss (MSE): {loss.item()}')
    print('-'*100)

Initial weights: Parameter containing:
tensor([[1.]], requires_grad=True)
Initial bias: Parameter containing:
tensor([0.5000], requires_grad=True)

Outputs: tensor([[1.5000],
        [2.5000],
        [3.5000],
        [4.5000]], grad_fn=<AddmmBackward0>)

Epoch 1, Loss (MSE): 0.25
----------------------------------------------------------------------------------------------------
Initial weights: Parameter containing:
tensor([[1.0250]], requires_grad=True)
Initial bias: Parameter containing:
tensor([0.5100], requires_grad=True)

Outputs: tensor([[1.5350],
        [2.5600],
        [3.5850],
        [4.6100]], grad_fn=<AddmmBackward0>)

Epoch 2, Loss (MSE): 0.18353763222694397
----------------------------------------------------------------------------------------------------
Initial weights: Parameter containing:
tensor([[1.0458]], requires_grad=True)
Initial bias: Parameter containing:
tensor([0.5185], requires_grad=True)

Outputs: tensor([[1.5643],
        [2.6100],
        [3.6558]